"""Upgrade users table to include city, state, zip code, and country.

Revision ID: 221a02df03d8
Revises: fb392739fcdd
Create Date: 2020-11-28 11:02:12.570850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221a02df03d8'
down_revision = 'fb392739fcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
